server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: Linky-App
  datasource:
    url: jdbc:mysql://localhost:3307/linky_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hop2005@
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri:
            scope: email,profile,openid
        provider:
          user-info-uri:
  jwt:
    expiration: 3600 #hours = 1 * 60 * 60
    expiration-refresh-token: 86400 #days =  24 * 60 * 60
    secretKeyAccess: c29tZUNvbXBsZXhLZXlzZWN1cml0eTEyMzQ1Njc4OTA=
  client:
    uri: http://localhost:3000
logging:
  level:
    org:
      springframework.security: DEBUG
